name: JMIN
favicon: null
layout_spectrum: 0.8532884
typography_spectrum: 0.55646
title: JapanMinute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9f9f9f'
    - '#838383'
    - '#d0d0d0'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
