name: JMIN
favicon: null
layout_spectrum: 0.81717
typography_spectrum: 0.88157
title: JapanMinute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#ffffff'
    - '#ff1e22'
    - '#901e1e'
    - '#6a6562'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
